---
kind: pipeline
name: durl
steps:
- name: durl
  image: quay.io/suzuki_shunsuke/durl:1.0.0
  commands:
  - sh scripts/durl.sh
---
kind: pipeline
name: shell scripts
clone:
  depth: 1
steps:
- name: shellcheck
  image: koalaman/shellcheck-alpine:v0.7.0
  commands:
  - 'find . -name "*.sh" -print0 | xargs -0 shellcheck env.sh.tmpl'
- name: shfmt
  image: mvdan/shfmt:v3.0.0
  commands:
  - 'find . -name "*.sh" -print0 | xargs -0 shfmt -l -w env.sh.tmpl'
---
kind: pipeline
name: yamllint
steps:
- name: yamllint
  image: quay.io/suzuki_shunsuke/yamllint:1.20.0__1
  commands:
  - 'find . \( -name "*.yml" -o -name "*.yaml" \) -print0 | xargs -0 yamllint -c .yamllint.yml'
---
kind: pipeline
name: jsonlint
steps:
- name: jsonlint
  image: cytopia/jsonlint:1.6.0-0.5
  commands:
  - bash scripts/jsonlint.sh
---
kind: pipeline
name: terraform fmt (v0.12)
steps:
- name: terraform fmt (v0.12)
  image: hashicorp/terraform:0.12.19
  commands:
  - terraform fmt -check terraform/example/v0.12
  - terraform fmt -check -recursive testdata
---
kind: pipeline
name: terraform fmt (v0.11)
steps:
- name: terraform fmt (v0.11)
  image: hashicorp/terraform:0.11.14
  commands:
  - cd terraform/example/v0.11
  - terraform fmt -check
---
kind: pipeline
name: build
volumes:
- name: gopath
  temp: {}
steps:
- name: download go modules
  image: &image_go golang:1.13.6
  commands:
  - go mod download
  volumes: &volumes
  - name: gopath
    path: /go
  environment:
    GOPATH: /go
- name: golangci-lint
  image: golangci/golangci-lint:v1.22.2-alpine
  commands:
  - golangci-lint run
  volumes: *volumes
  environment:
    GOPATH: /go
- name: codecov
  image: *image_go
  commands:
  # bash and cgo seem to be required
  - bash scripts/codecov_test.sh
  - curl -s https://codecov.io/bash > /tmp/codecov.sh
  - test "$LOCAL" = "true" -o "$DRONE_BUILD_EVENT" = "pull_request" || bash /tmp/codecov.sh
  volumes: *volumes
  environment:
    GOPATH: /go
    CODECOV_TOKEN:
      from_secret: codecov_token
- name: remove changes
  image: &image_git plugins/git
  commands:
  # Sometimes it is failed to release by goreleaser due to changes of go.sum
  - git checkout -- .

- name: fetch tags to release
  image: *image_git
  commands:
  - git fetch --tags
  when:
    event:
    - tag
- name: release
  image: &goreleaser goreleaser/goreleaser:v0.123.3
  commands:
  - goreleaser release
  environment:
    GOPATH: /go
    GITHUB_TOKEN:
      from_secret: github_token
  volumes: *volumes
  when:
    event:
    - tag

- name: create a dummy tag to test releasing
  image: *image_git
  commands:
  - git tag v0.1.0-alpha
  when:
    event:
    - pull_request
    - push
- name: release (skip-publish)
  image: *goreleaser
  commands:
  - goreleaser release --skip-publish
  environment:
    GOPATH: /go
  volumes: *volumes
  when:
    event:
    - pull_request
    - push
