---
kind: pipeline
name: commitlint
steps:
- name: npm install
  image: &node_image node:10.16.0-alpine
  commands:
  - npm i
- name: tag/commitlint
  image: *node_image
  commands:
  - npx commitlint --from HEAD~1 --to HEAD
  when:
    event:
    - tag
    - push
- name: pr/commitlint
  image: *node_image
  commands:
  - npx commitlint --from master --to HEAD || exit 1
  when:
    event:
    - pull_request
---
kind: pipeline
name: build
workspace:
  base: /go
  path: src/github.com/suzuki-shunsuke/go-graylog
steps:
- name: download go modules
  image: &image_go golang:1.12.6
  commands:
  - go mod download
  environment:
    GO111MODULE: on
    GOPATH: /go
- name: golangci-lint
  image: golangci/golangci-lint:v1.17.1
  commands:
  - golangci-lint run
  environment:
    GO111MODULE: on
    GOPATH: /go
- name: codecov
  image: *image_go
  commands:
  # bash and cgo seem to be required
  - bash scripts/codecov-test.sh
  - curl -s https://codecov.io/bash > /tmp/codecov.sh
  - test "$LOCAL" = "true" -o "$DRONE_BUILD_EVENT" = "pull_request" || bash /tmp/codecov.sh
  environment:
    GO111MODULE: on
    GOPATH: /go
    CODECOV_TOKEN:
      from_secret: codecov_token
- name: build
  image: &image_gox suzukishunsuke/gox:1.0.1__0.1.0
  commands:
  - gox -output="dist/${DRONE_TAG}/terraform-provider-graylog_${DRONE_TAG}_{{.OS}}_{{.Arch}}" -osarch="darwin/amd64 linux/amd64 windows/amd64" ./terraform/
  - ls dist/${DRONE_TAG} | xargs -I {} gzip dist/${DRONE_TAG}/{}
  environment:
    GOPATH: /go
    GO111MODULE: on
  when:
    event:
    - tag
- name: build test
  image: *image_gox
  commands:
  - gox -output="dist/v0.1.0/terraform-provider-graylog_v0.1.0_{{.OS}}_{{.Arch}}" -osarch="darwin/amd64 linux/amd64 windows/amd64" ./terraform/
  - ls dist/v0.1.0 | xargs -I {} gzip dist/v0.1.0/{}
  environment:
    GOPATH: /go
    GO111MODULE: on
  when:
    event:
    - push
    - pull_request
- name: release
  image: suzukishunsuke/ghr
  commands:
  - ghr -u suzuki-shunsuke -r go-graylog ${DRONE_TAG} dist/${DRONE_TAG}
  environment:
    GITHUB_TOKEN:
      from_secret: github_token
  when:
    event:
    - tag
